### ISSUE TITLE
Fix "developped"

### ISSUE THREAD

**Issue by tjklint** [carsonSgit/carsonSgit#1]
On your README.md the following sentence reads as such:

- Currently, I'm working on an IoT project developped using Python and MAUI, with Microsoft Azure as our IoT communication

To fix: "developped" should be "developed"

**Comment by tjklint** [comment]
![image](https://github.com/carsonSgit/carsonSgit/assets/112092190/495fce58-c625-4d05-a5b4-9fddd05ec3c6)

Further proof.

**Comment by carsonSgit** [comment]
Resolved. Closing issue.
